# Generated by Django 5.0.1 on 2024-03-11 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticlink',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата Дата и время'),
        ),
    ]
