# Generated by Django 5.0.1 on 2024-01-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentbanner',
            options={'verbose_name': 'контент', 'verbose_name_plural': 'Баннер'},
        ),
    ]
