# Generated by Django 5.0 on 2023-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0002_alter_formuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
