# Generated by Django 5.0.1 on 2024-03-18 17:17

import appResponse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedate',
            name='status',
            field=models.BooleanField(blank=True, default=True, help_text='Да (Активный) / Нет (Неактивный)', null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='generatenumber',
            name='number',
            field=models.IntegerField(default=appResponse.models.generate_number, verbose_name='Число'),
        ),
    ]
