# Generated by Django 5.0.1 on 2024-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducrShop',
            new_name='ProductShop',
        ),
    ]
