# Generated by Django 5.0 on 2024-02-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0003_product_currency_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RU', 'Рубль'), ('USD', 'Доллар'), ('CHINA', 'Юань'), ('EU', 'Евро')], default='RU', max_length=50, verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('photo', models.ImageField(upload_to='ProductPhotos', verbose_name='Изображение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appKey.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'фото товара',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
    ]
