# Generated by Django 5.0 on 2024-02-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0004_alter_product_currency_productphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphotos',
            name='title',
        ),
    ]
