# Generated by Django 5.0.1 on 2024-02-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0005_remove_productphotos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appKey.product', verbose_name='Продукт'),
        ),
    ]
