# Generated by Django 5.0.1 on 2024-03-04 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
                ('name_url', models.CharField(max_length=10, verbose_name='Имя ссылки')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
